name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}
  merge_group:
    types: [checks_requested]

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm lint

  # default_tests:
  #   name: Default Tests
  #   timeout-minutes: 5
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: wyvox/action-setup-pnpm@v3
  #     - run: pnpm test 
  #
  # floating_tests:
  #   name: Floating Deps Test
  #   timeout-minutes: 5
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: wyvox/action-setup-pnpm@v3
  #       with:
  #         args: '--no-lockfile' 
  #     - run: pnpm test 

